# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "fb5cc171-3064-45fc-989d-2b7fa8af194c"

  # Web app name
  webAppName: "viewtechlabs"

  # Environment name
  environmentName: "viewtechlabs"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - checkout: self
          - checkout: git://viewtech-labs/viewtech-labs-api@main
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          - script: |
              dir $(Build.SourcesDirectory)
              cd $(Build.SourcesDirectory)/viewtech-labs-api 
              npm install
            displayName: "npm install nodejs"
          - script: |
              cd $(Build.SourcesDirectory)/viewtech-labs
              npm install
              npm run build              
              echo $(Build.SourcesDirectory)
          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/viewtech-labs/build
              Contents: "**"
              TargetFolder: $(Build.SourcesDirectory)/viewtech-labs-api/build
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/viewtech-labs-api"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: "Azure Web App Deploy: viewtechlabs"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    appName: $(webAppName)
                    runtimeStack: "NODE|18.12.1"
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                    startUpCommand: "npm run start"
